TotalResults: 1
ReturnedResults: 1
Results:
- Resume:
    ExternalResumeID: XR******************
    ResumeFileName:
    ResumeData:
    ResumeExtension:
    ResumeTitle:
  IsSubmitted: false
  VID: Visitor ID
  BID: Browser ID
  SID: Session ID
  SiteID: Site ID
  IPathID: IPath
  ApplicationDID: JA******************
  CoverLetter:
    CoverLetterID:
    CoverLetterText:
    CoverLetterTitle:
  Responses:
  - QuestionID: ApplicantName
    ResponseText: name
  - QuestionID: ApplicantEmail
    ResponseText: Email
  - QuestionID: Resume
    ResponseText: Resume Text will be returned here.
  TNDID:
  ExternalUserID: XR******************
  redirectURL:
Errors: []
Timestamp: '2013-12-05T14:02:51.9490777-05:00'
Status: Success
